services:
  postgres:
    image: postgres:alpine

    ports:
      - 5432:5432
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - ~/docker/volumes/postgresql/data:/var/lib/postgresql/data

  # optional postgresql web based tools
  pgadmin:
    image: dpage/pgadmin4

    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
      - postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
