services:
  postgres:
    image: postgres:alpine
    container_name: postgres_container
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  # optional postgresql admin tool
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    depends_on:
      - postgres
    
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
